import { Luckiest_Guy, Zilla_Slab } from "next/font/google";
import { Toaster } from "react-hot-toast";

import { Header } from "@/components/header";
import BG from "@/assets/images/backgrounds/body.jpg";
import { ReduxProvider } from "@/components/providers/reduxProvider";
import NextAuthProvider from "@/components/providers/nextAuthProvider";

import "./globals.css";

const LuckiestGuy = Luckiest_Guy({ subsets: ["latin"], weight: "400" });
const ZillaSlab = Zilla_Slab({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
});

export const metadata = {
  title: "Triple Shot Cafe",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${LuckiestGuy.className} ${ZillaSlab.className}`}
        style={{ background: `url(${BG.src})` }}
      >
        <ReduxProvider>
          <NextAuthProvider>
            <Toaster toastOptions={{ duration: 4000 }} />
            <Header />
            {children}
          </NextAuthProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}
