import { Header } from "@/components/header";
import "./globals.css";
import { Luckiest_Guy, Zilla_Slab } from "next/font/google";
import BG from "@/assets/images/backgrounds/body.jpg";

const LuckiestGuy = Luckiest_Guy({ subsets: ["latin"], weight: "400" });
const ZillaSlab = Zilla_Slab({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
});

export const metadata = {
  title: "Triple Shot Cafe",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${LuckiestGuy.className} ${ZillaSlab.className}`}
        style={{ background: `url(${BG.src})` }}
      >
        <Header />
        {children}
      </body>
    </html>
  );
}
